var tableauQuestion = [
    {   question : "Si vous conduisez à 80km/h, que vous approchez d'une zone résidentielle, vous devez donc :",
        propositionA : "Accélérer",
        propositionB : "Maintenir votre vitesse, si vous ne croisez pas d'autres véhicules",
        propositionC : "Ralentir",
        propositionD : "Maintenir votre vitesse",
        reponse : "C"},

    {   question : "Vous vous apprétez à tourner à droite au feu vert, mais vous voyez un piéton qui traverse :",
        propositionA : "Vous passez avant le piéton",
        propositionB : "Vous vérifiez qu'il n'y a pas d'autre véhicule et vous passez",
        propositionC : "Vous attendez que le piéton est traversé",
        propositionD : "Vous écrasez le piéton pour passer",
        reponse : "C"},

    {   question : "Sans aucune indication : La vitesse dans une zone résidentielle est de : __ km/h",
        propositionA : "50",
        propositionB : "55",
        propositionC : "65",
        propositionD : "70",
        reponse : "A"},

	{   question : "Avant chaque changement de file vous devez :",
        propositionA : "Vérifier vos rétroviseurs",
        propositionB : "Vérifier vos angles morts",
        propositionC : "Signaler vos intentions",
        propositionD : "Les trois autres propositions",
        reponse : "D"},

	{   question : "A quel taux d'alcoolémie est-on considéré comme inapte à prendre le volant ?",
        propositionA : "0,40g/L",
        propositionB : "0,25g/L",
        propositionC : "0,2g/L",
        propositionD : "0,1g/L",
        reponse : "C"},

	{   question : "A quel moment vous pouvez passer au feu ?",
        propositionA : "Quand il est vert",
        propositionB : "Quand il n'y a personne à l'intersection",
        propositionC : "Vous êtes à proximité d'une école",
        propositionD : "Quand il est vert ou rouge et que je tourne à droite",
        reponse : "D"},

	{   question : "Un piéton est à son feu rouge",
        propositionA : "Vous le laissez passer",
        propositionB : "Vous observez avant de continuer",
        propositionC : "Vous lui faite un signe de la main",
        propositionD : "Vous continuez votre chemin car votre feu est vert",
        reponse : "D"},

	{   question : "Qu'est ce qui est permit quand vous dépassez un autre véhicule",
        propositionA : "Le suivre de près pour le doubler plus vite",
        propositionB : "Le doubler en quittant la route",
        propositionC : "Conduire sur la voie opposée pour le dépasser",
        propositionD : "Dépasser la vitesse limite",
        reponse : "C"},

	{   question : "Vous conduisez sur une rocade qui indique une vitesse maximum de 110 km/h. La plupart du traffic roule à 120 km/h, alors vous ne devriez pas conduire plus vite que :",
        propositionA : "80 kmh",
        propositionB : "40 kmh",
        propositionC : "110 kmh",
        propositionD : "120 kmh",
        reponse : "C"},

	{   question : "Quand vous êtes dépassé par un autre véhicule il est important de ne pas :",
        propositionA : "Ralentir",
        propositionB : "Vérifier vos rétroviseurs",
        propositionC : "Regarder les autres conducteurs",
        propositionD : "Augmenter votre vitesse",
        reponse : "D"},
]
